% Author: Jean-Philippe Raymond (raymonjp@iro.umontreal.ca)
% =========================================================


function doesNotContainDuplicate = containsOnlyUniquePaths(choiceSet)
    %{
    TODO: Bla bla bla ...

    choiceSet is expected to have a count in the first column (i.e. it is
    expected to be formatted like the paths generated by pathGeneration.m).
    %}

    choiceSetSize = size(choiceSet, 1);
    doesNotContainDuplicate = size(uniquePaths(choiceSet, choiceSetSize), 1) == choiceSetSize;
end
