% Author: Jean-Philippe Raymond (raymonjp@iro.umontreal.ca)
% =========================================================


function structure = predictionsStruct(nPredictions)
    %{
    TODO: Bla bla bla ...
    %}

    structure = repmat(struct('obsID', 0, ...
                              'path', [], ...
                              'count', 1, ...
                              'utility', 0.0, ...
                              'probability', 0.0), ...
                       nPredictions, 1);
    % The count field indicates the number of times the alternative was drawn
    % during sampling.
end
